version: 2.1

jobs:
  install:
    working_directory: /go/src/github.com/clarke94/serverfx
    docker:
        - image: circleci/golang:1.17.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  lint:
    working_directory: /go/src/github.com/clarke94/serverfx
    docker:
      - image: circleci/golang:1.17.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Run Linting
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.43.0
            make lint

  test:
    working_directory: /go/src/github.com/clarke94/serverfx
    docker:
      - image: circleci/golang:1.17.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Run tests
          command: make test

  publish:
    working_directory: /go/src/github.com/clarke94/serverfx
    docker:
      - image: circleci/golang:1.17.3
    steps:
      - checkout
      - run: go get -u github.com/tcnksm/ghr
      - run:
          name: Release
          command: |
            VERSION=<< pipeline.git.tag	>>
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION}
      - run:
          name: Index
          command: |
            VERSION=<< pipeline.git.tag	>>
            GOPROXY=proxy.golang.org go list -m github.com/clarke94/serverfx@${VERSION}


workflows:
  build-and-publish:
    jobs:
      - install:
          filters:
            tags:
              only: /^v.*/
      - lint:
          requires:
            - install
          filters:
            tags:
              only: /^v.*/
      - test:
          requires:
            - install
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - test
            - lint
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/